In [1]:
import numpy as np

## simple activation function

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [41]:
def relu(x):
    return np.maximum(0, x)

In [43]:
def softmax(a):
    c = np.max(a) # overflow 방지를 위해
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [47]:
x = np.array([0.5, 0.1, -0.2])
sigmoid(x)
relu(x) # gradient vanishing 문제 대처, leaky relu도 고려할 것
softmax(x) # 총 합이 1이고 따라서 출력을 확률로 이해할 수 있음

array([0.46148762, 0.3093444 , 0.22916797])

## deal with multi dimensional data

In [8]:
import numpy as np

In [17]:
A = np.array([
    [1, 2], [3, 4]
    ])
np.ndim(A) # 2 차원
A.shape # (2, 2)

(2, 2)

In [18]:
A = np.array([
    [1, 2], [3, 4]
])
B = np.array([
    [5, 6], [7, 8]
])

print(A.shape, B.shape)


(2, 2) (2, 2)


In [23]:
print(np.dot(A, B)) # 행렬곱
print(A * B) # 데카르트 곱 (원소끼리 단순히 곱한 것)


[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [28]:
A=np.array([1, 2])
A.shape # (2,) 주의할 점이, np.dot에서 앞에 오면 1행 2열, 뒤에 오면 2행 1열으로 알아서 변환이 됨

(2,)

In [37]:
B=np.array([[1, 2], [3, 4]]) # (2, 2)
np.dot(A, B) # (1, 2) * (2, 2) -> (1, 2) -> (2, )
np.dot(B, A) # (2, 2) * (2, 1) -> (2, 1) -> (2, )

array([ 5, 11])

## forward propagation

In [50]:
import sys, os
sys.path.append(os.pardir)
from dataset.mnist import load_mnist

In [51]:
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=False, flatten=True)

Converting train-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting train-labels-idx1-ubyte.gz to NumPy Array ...
Done
Converting t10k-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting t10k-labels-idx1-ubyte.gz to NumPy Array ...
Done
Creating pickle file ...
Done!


In [54]:
print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)


(60000, 784)
(60000,)
(10000, 784)
(10000,)
