In [2]:
import torch

In [3]:
print(torch.tensor([[1, 2], [3, 4]]))
print(torch.tensor([[1, 2], [3, 4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [5]:
tmp = torch.tensor([[1, 2], [3, 4]])
print(tmp.numpy())

[[1 2]
 [3 4]]


In [8]:
tmp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7, 8])

tensor([5., 6., 7.])

In [9]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([4, 5, 6])
v + w

tensor([5, 7, 9])

In [16]:
tmp = torch.tensor([[1, 2], [3, 4]])
print(tmp.shape)
print(tmp.size())
print(tmp.view(4, 1)) # 2, 2 -> 4, 1
print(tmp.view(1, -1)) # 2, 2 -> 1, 4

torch.Size([2, 2])
torch.Size([2, 2])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2, 3, 4]])
